import { Dispatch, SetStateAction } from "react";
import {
  ScheduleData,
  ScheduleEventType,
  PlenumEvent,
  CommitteeEvent,
  KnsEvent,
  CommitteeParticipantsData,
  CommitteeParticipant,
} from "./ScheduleDataTypes";

import axios from "axios";
import Papa from "papaparse";
import { head } from "axios";
/*
 * Fetch data from the Knesset API
 * @param url - the url to fetch data from
 * @param requestInit - the request options
 * @returns the fetched data
 */
export async function fetchData(url: string, requestInit?: RequestInit) {
  try {
    const response = await fetch(url, requestInit);
    if (!response.ok) {
      throw new Error(`Failed to fetch data: ${response.statusText}`);
    }
    const data = await response.json();
    // console.log(data);
    return data;
  } catch (error) {
    console.error("Error fetching data:", error);
    return [];
  }
}

/*
 * Fetch schedule data from the Knesset API
 * @param date - the date to fetch data for
 * @param setEvents - a function to set the fetched data
 * @param id - the id of the event to fetch, if -1 so fetch all events
 * @param type - the type of the event to fetch, relevant only if id is not -1m
 * @returns the fetched schedule data
 */
export async function fetchScheduleData(
  date: string,
  id: number,
  type: ScheduleEventType,
  setLoading?: Dispatch<SetStateAction<boolean>>,
  setEvents?: Dispatch<SetStateAction<ScheduleData>>
): Promise<any> {
  try {
    const rawScheduleData = await fetchData(
      "https://knesset.gov.il/WebSiteApi/knessetapi/KnessetMainEvents/GetEventsAgendaToday",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ SelectedDate: date, SelectedMonth: null, SelectedYear: null }),
      }
    );
    const committeeParticipantsData = await fetchData(
      "https://knesset.gov.il/WebSiteApi/knessetapi/MkLobby/GetMkLobbyData?lang=he"
    );
    // console.log(await CommitteesData);
    const scheduleData: ScheduleData = {
      eventsNumber:
        rawScheduleData.CurrentCommitteeEvents.length +
        rawScheduleData.CurrentPlenumEvents.length +
        rawScheduleData.CurrentKnsEvents.length,
      CurrentDateText: rawScheduleData.CurrentDateText,
      CurrentPlenumEvents: rawScheduleData.CurrentPlenumEvents.length == 0 ? [] : processPlenumEvents(rawScheduleData),
      CurrentCommitteeEvents:
        rawScheduleData.CurrentCommitteeEvents.length == 0
          ? []
          : processCommitteeEvents(rawScheduleData, committeeParticipantsData),
      CurrentKnsEvents: rawScheduleData.CurrentKnsEvents.length == 0 ? [] : processKnsEvents(rawScheduleData),
    };
    console.log(scheduleData);
    if (setEvents) {
      setEvents(scheduleData);
    }
    if (id == -1) {
      return scheduleData;
    } else {
      if (type == ScheduleEventType.Committee) {
        return scheduleData.CurrentCommitteeEvents[id];
      } else if (type == ScheduleEventType.Plenum) {
        return scheduleData.CurrentPlenumEvents[id];
      } else {
        return scheduleData.CurrentKnsEvents[id];
      }
    }
  } catch (error) {
    console.error("Error fetching schedule data:", error);
    if (id != -1) {
      return null;
    }
    return {
      CommiteesNumber: 0,
      CurrentDateText: "",
      CurrentPlenumEvents: [],
      CurrentCommitteeEvents: [],
      CurrentKnsEvents: [],
    };
  } finally {
    if (setLoading) setLoading(false);
  }
}

/*
 * Process the fetched data of special occasions
 * @param data - the fetched data
 * @returns the processed data
 */
function processKnsEvents(data: ScheduleData): KnsEvent[] {
  return data.CurrentKnsEvents?.map((event: any, index: number) => {
    const cleanName: string = event.EventName.replace(/<\/?[^>]+(>|$)/g, "")
      .replace(/\d{2}:\d{2}/, "")
      .trim();
    const groups = event.groups
      .replace(/\s+/g, "")
      .split(",")
      .map((group: string) => parseInt(group));
    return {
      id: index,
      EventStart: new Date(event.EventStart),
      EventType: event.EventType,
      EventName: cleanName,
      rnkParent: event.rnkParent,
      groups: groups,
      rnkChilds: event.rnkChilds,
    };
  });
}
/*
 * Process the fetched data of committee events
 * @param data - the fetched data
 * @returns the processed data
 */
function processCommitteeEvents(data: ScheduleData, committeesParticipantsData: any): CommitteeEvent[] {
  return data.CurrentCommitteeEvents?.map((event: any, index: number) => {
    let names: string[] = ["", ""];
    if (event.EventName != null) {
      names = event.EventName?.split("</p>");
    }
    const committeeName = names[0]?.replace(/<\/?[^>]+(>|$)/g, "").trim();
    const eventName = names[1]?.replace(/<\/?[^>]+(>|$)/g, "").trim();
    let groups: number[] = [];
    if (event.groups != null) {
      groups = event.groups
        .replace(/\s+/g, "")
        .split(",")
        .map((group: string) => parseInt(group));
    }
    const filteredParticipants = committeesParticipantsData.committeePresences.filter(
      (participant: any) => participant.CommitteeName === committeeName
    );
    const participants: CommitteeParticipant[] = committeesParticipantsData.mks
      .filter((mks: any) => {
        return filteredParticipants.some((participant: any) => participant.MkId === mks.MkId);
      })
      .map((mk: any) => {
        return {
          ParticipantId: mk.MkId,
          ParticipantName: `${mk.Firstname} ${mk.Lastname}`,
          ParticipantRole: filteredParticipants.find((participant: any) => participant.MkId === mk.MkId).RoleName,
          ParticipantImage: mk.ImagePath,
        };
      });
    return {
      id: index,
      EventStart: new Date(event.EventStart),
      IsCanceled: event.IsCanceled,
      EventName: eventName,
      CommitteeName: committeeName,
      CommitteeId: 0,
      EventDiscription: "",
      EventParticipants: participants,
      EventLiveStream: "",
    };
  });
}
/*
 * Process the fetched data of plenum events
 * @param data - the fetched data
 * @returns the processed data
 */
function processPlenumEvents(data: ScheduleData): PlenumEvent[] {
  return data.CurrentPlenumEvents?.map((event: any, index: number) => {
    return {
      id: index,
      RowNum: isNaN(event.RowNum) ? 0 : event.RowNum,
      EventStart: new Date(event.startTime),
      SessionNumber: event.SessionNumber,
      SessionTitleStr: event.SessionTitleStr,
      FK_SessionID: event.FK_SessionID,
      Name: event.Name?.indexOf("(") == -1 ? event.Name : event.Name?.substring(0, event.Name?.indexOf("(")),
      FK_ItemID: event.FK_ItemID,
      IsBill: event.IsBill,
      IsAgendaSug: event.IsAgendaSug,
      FK_StatusID: event.FK_StatusID,
    };
  });
}

//create a function that fetches csv data from the url https://production.oknesset.org/pipelines/data/committees/kns_committeesession/kns_committeesession.csv
// in addition, the function will filter the rows according to one column and return the data

export async function fetchCommitteeData(committee: CommitteeEvent) {
  try {
    console.log("starting fetch CSV file");
    const response = await axios.get("/api-schedule");
    const responseData = response.data as {
      query_result: { data: { rows: any[] } };
    };
    // const parsedData = Papa.parse(csvText, {
    //   header: true,
    //   skipEmptyLines: true,
    // });
    console.log(responseData.query_result.data);
    // return parsedData.data.filter((row) => row[filterColumn] === filterValue);
  } catch (error) {
    console.error("Error fetching or parsing CSV data:", error);
    throw error;
  }
}

[
  {
    CommitteeId: 1,
    CommitteeName: "ועדת הכנסת",
    RoleId: 4,
    MkId: 976,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/knesset/Pages/default.aspx",
  },
  {
    CommitteeId: 1,
    CommitteeName: "ועדת הכנסת",
    RoleId: 6,
    MkId: 970,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/knesset/Pages/default.aspx",
  },
  {
    CommitteeId: 1,
    CommitteeName: "ועדת הכנסת",
    RoleId: 6,
    MkId: 1088,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/knesset/Pages/default.aspx",
  },
  {
    CommitteeId: 1,
    CommitteeName: "ועדת הכנסת",
    RoleId: 6,
    MkId: 1095,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/knesset/Pages/default.aspx",
  },
  {
    CommitteeId: 1,
    CommitteeName: "ועדת הכנסת",
    RoleId: 6,
    MkId: 915,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/knesset/Pages/default.aspx",
  },
  {
    CommitteeId: 1,
    CommitteeName: "ועדת הכנסת",
    RoleId: 6,
    MkId: 1044,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/knesset/Pages/default.aspx",
  },
  {
    CommitteeId: 1,
    CommitteeName: "ועדת הכנסת",
    RoleId: 6,
    MkId: 1026,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/knesset/Pages/default.aspx",
  },
  {
    CommitteeId: 1,
    CommitteeName: "ועדת הכנסת",
    RoleId: 6,
    MkId: 872,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/knesset/Pages/default.aspx",
  },
  {
    CommitteeId: 1,
    CommitteeName: "ועדת הכנסת",
    RoleId: 6,
    MkId: 208,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/knesset/Pages/default.aspx",
  },
  {
    CommitteeId: 1,
    CommitteeName: "ועדת הכנסת",
    RoleId: 6,
    MkId: 1119,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/knesset/Pages/default.aspx",
  },
  {
    CommitteeId: 1,
    CommitteeName: "ועדת הכנסת",
    RoleId: 6,
    MkId: 1106,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/knesset/Pages/default.aspx",
  },
  {
    CommitteeId: 1,
    CommitteeName: "ועדת הכנסת",
    RoleId: 6,
    MkId: 1109,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/knesset/Pages/default.aspx",
  },
  {
    CommitteeId: 1,
    CommitteeName: "ועדת הכנסת",
    RoleId: 6,
    MkId: 1110,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/knesset/Pages/default.aspx",
  },
  {
    CommitteeId: 1,
    CommitteeName: "ועדת הכנסת",
    RoleId: 6,
    MkId: 987,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/knesset/Pages/default.aspx",
  },
  {
    CommitteeId: 1,
    CommitteeName: "ועדת הכנסת",
    RoleId: 6,
    MkId: 1117,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/knesset/Pages/default.aspx",
  },
  {
    CommitteeId: 1,
    CommitteeName: "ועדת הכנסת",
    RoleId: 6,
    MkId: 1067,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/knesset/Pages/default.aspx",
  },
  {
    CommitteeId: 1,
    CommitteeName: "ועדת הכנסת",
    RoleId: 6,
    MkId: 905,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/knesset/Pages/default.aspx",
  },
  {
    CommitteeId: 2,
    CommitteeName: "ועדת הכספים",
    RoleId: 4,
    MkId: 35,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/Finance/Pages/default.aspx",
  },
  {
    CommitteeId: 2,
    CommitteeName: "ועדת הכספים",
    RoleId: 6,
    MkId: 970,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Finance/Pages/default.aspx",
  },
  {
    CommitteeId: 2,
    CommitteeName: "ועדת הכספים",
    RoleId: 6,
    MkId: 1088,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Finance/Pages/default.aspx",
  },
  {
    CommitteeId: 2,
    CommitteeName: "ועדת הכספים",
    RoleId: 6,
    MkId: 1049,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Finance/Pages/default.aspx",
  },
  {
    CommitteeId: 2,
    CommitteeName: "ועדת הכספים",
    RoleId: 6,
    MkId: 1100,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Finance/Pages/default.aspx",
  },
  {
    CommitteeId: 2,
    CommitteeName: "ועדת הכספים",
    RoleId: 6,
    MkId: 1032,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Finance/Pages/default.aspx",
  },
  {
    CommitteeId: 2,
    CommitteeName: "ועדת הכספים",
    RoleId: 6,
    MkId: 208,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Finance/Pages/default.aspx",
  },
  {
    CommitteeId: 2,
    CommitteeName: "ועדת הכספים",
    RoleId: 6,
    MkId: 1120,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Finance/Pages/default.aspx",
  },
  {
    CommitteeId: 2,
    CommitteeName: "ועדת הכספים",
    RoleId: 6,
    MkId: 1105,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Finance/Pages/default.aspx",
  },
  {
    CommitteeId: 2,
    CommitteeName: "ועדת הכספים",
    RoleId: 6,
    MkId: 1107,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Finance/Pages/default.aspx",
  },
  {
    CommitteeId: 2,
    CommitteeName: "ועדת הכספים",
    RoleId: 6,
    MkId: 992,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Finance/Pages/default.aspx",
  },
  {
    CommitteeId: 2,
    CommitteeName: "ועדת הכספים",
    RoleId: 6,
    MkId: 837,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Finance/Pages/default.aspx",
  },
  {
    CommitteeId: 2,
    CommitteeName: "ועדת הכספים",
    RoleId: 6,
    MkId: 1001,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Finance/Pages/default.aspx",
  },
  {
    CommitteeId: 2,
    CommitteeName: "ועדת הכספים",
    RoleId: 6,
    MkId: 978,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Finance/Pages/default.aspx",
  },
  {
    CommitteeId: 2,
    CommitteeName: "ועדת הכספים",
    RoleId: 6,
    MkId: 1114,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Finance/Pages/default.aspx",
  },
  {
    CommitteeId: 2,
    CommitteeName: "ועדת הכספים",
    RoleId: 6,
    MkId: 1111,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Finance/Pages/default.aspx",
  },
  {
    CommitteeId: 2,
    CommitteeName: "ועדת הכספים",
    RoleId: 6,
    MkId: 1112,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Finance/Pages/default.aspx",
  },
  {
    CommitteeId: 2,
    CommitteeName: "ועדת הכספים",
    RoleId: 6,
    MkId: 948,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Finance/Pages/default.aspx",
  },
  {
    CommitteeId: 3,
    CommitteeName: "ועדת הכלכלה",
    RoleId: 4,
    MkId: 914,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/Economics/Pages/default.aspx",
  },
  {
    CommitteeId: 3,
    CommitteeName: "ועדת הכלכלה",
    RoleId: 6,
    MkId: 1088,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Economics/Pages/default.aspx",
  },
  {
    CommitteeId: 3,
    CommitteeName: "ועדת הכלכלה",
    RoleId: 6,
    MkId: 1097,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Economics/Pages/default.aspx",
  },
  {
    CommitteeId: 3,
    CommitteeName: "ועדת הכלכלה",
    RoleId: 6,
    MkId: 1042,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Economics/Pages/default.aspx",
  },
  {
    CommitteeId: 3,
    CommitteeName: "ועדת הכלכלה",
    RoleId: 6,
    MkId: 1125,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Economics/Pages/default.aspx",
  },
  {
    CommitteeId: 3,
    CommitteeName: "ועדת הכלכלה",
    RoleId: 6,
    MkId: 1101,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Economics/Pages/default.aspx",
  },
  {
    CommitteeId: 3,
    CommitteeName: "ועדת הכלכלה",
    RoleId: 6,
    MkId: 1090,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Economics/Pages/default.aspx",
  },
  {
    CommitteeId: 3,
    CommitteeName: "ועדת הכלכלה",
    RoleId: 6,
    MkId: 1013,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Economics/Pages/default.aspx",
  },
  {
    CommitteeId: 3,
    CommitteeName: "ועדת הכלכלה",
    RoleId: 6,
    MkId: 1061,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Economics/Pages/default.aspx",
  },
  {
    CommitteeId: 3,
    CommitteeName: "ועדת הכלכלה",
    RoleId: 6,
    MkId: 214,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Economics/Pages/default.aspx",
  },
  {
    CommitteeId: 3,
    CommitteeName: "ועדת הכלכלה",
    RoleId: 6,
    MkId: 1120,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Economics/Pages/default.aspx",
  },
  {
    CommitteeId: 3,
    CommitteeName: "ועדת הכלכלה",
    RoleId: 6,
    MkId: 1118,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Economics/Pages/default.aspx",
  },
  {
    CommitteeId: 3,
    CommitteeName: "ועדת הכלכלה",
    RoleId: 6,
    MkId: 1124,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Economics/Pages/default.aspx",
  },
  {
    CommitteeId: 3,
    CommitteeName: "ועדת הכלכלה",
    RoleId: 6,
    MkId: 982,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Economics/Pages/default.aspx",
  },
  {
    CommitteeId: 3,
    CommitteeName: "ועדת הכלכלה",
    RoleId: 6,
    MkId: 1018,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Economics/Pages/default.aspx",
  },
  {
    CommitteeId: 4,
    CommitteeName: "ועדת החוץ והביטחון",
    RoleId: 4,
    MkId: 1,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/ForeignAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 4,
    CommitteeName: "ועדת החוץ והביטחון",
    RoleId: 6,
    MkId: 970,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/ForeignAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 4,
    CommitteeName: "ועדת החוץ והביטחון",
    RoleId: 6,
    MkId: 1092,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/ForeignAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 4,
    CommitteeName: "ועדת החוץ והביטחון",
    RoleId: 6,
    MkId: 754,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/ForeignAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 4,
    CommitteeName: "ועדת החוץ והביטחון",
    RoleId: 6,
    MkId: 1088,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/ForeignAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 4,
    CommitteeName: "ועדת החוץ והביטחון",
    RoleId: 6,
    MkId: 1095,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/ForeignAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 4,
    CommitteeName: "ועדת החוץ והביטחון",
    RoleId: 6,
    MkId: 1022,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/ForeignAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 4,
    CommitteeName: "ועדת החוץ והביטחון",
    RoleId: 6,
    MkId: 1101,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/ForeignAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 4,
    CommitteeName: "ועדת החוץ והביטחון",
    RoleId: 6,
    MkId: 1044,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/ForeignAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 4,
    CommitteeName: "ועדת החוץ והביטחון",
    RoleId: 6,
    MkId: 1045,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/ForeignAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 4,
    CommitteeName: "ועדת החוץ והביטחון",
    RoleId: 6,
    MkId: 1050,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/ForeignAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 4,
    CommitteeName: "ועדת החוץ והביטחון",
    RoleId: 6,
    MkId: 874,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/ForeignAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 4,
    CommitteeName: "ועדת החוץ והביטחון",
    RoleId: 6,
    MkId: 881,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/ForeignAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 4,
    CommitteeName: "ועדת החוץ והביטחון",
    RoleId: 6,
    MkId: 1106,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/ForeignAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 4,
    CommitteeName: "ועדת החוץ והביטחון",
    RoleId: 6,
    MkId: 1121,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/ForeignAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 4,
    CommitteeName: "ועדת החוץ והביטחון",
    RoleId: 6,
    MkId: 1108,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/ForeignAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 4,
    CommitteeName: "ועדת החוץ והביטחון",
    RoleId: 6,
    MkId: 899,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/ForeignAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 5,
    CommitteeName: "ועדת הפנים והגנת הסביבה",
    RoleId: 4,
    MkId: 861,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/InternalAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 5,
    CommitteeName: "ועדת הפנים והגנת הסביבה",
    RoleId: 6,
    MkId: 1088,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/InternalAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 5,
    CommitteeName: "ועדת הפנים והגנת הסביבה",
    RoleId: 6,
    MkId: 1045,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/InternalAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 5,
    CommitteeName: "ועדת הפנים והגנת הסביבה",
    RoleId: 6,
    MkId: 1060,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/InternalAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 5,
    CommitteeName: "ועדת הפנים והגנת הסביבה",
    RoleId: 6,
    MkId: 1026,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/InternalAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 5,
    CommitteeName: "ועדת הפנים והגנת הסביבה",
    RoleId: 6,
    MkId: 1030,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/InternalAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 5,
    CommitteeName: "ועדת הפנים והגנת הסביבה",
    RoleId: 6,
    MkId: 998,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/InternalAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 5,
    CommitteeName: "ועדת הפנים והגנת הסביבה",
    RoleId: 6,
    MkId: 1105,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/InternalAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 5,
    CommitteeName: "ועדת הפנים והגנת הסביבה",
    RoleId: 6,
    MkId: 1119,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/InternalAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 5,
    CommitteeName: "ועדת הפנים והגנת הסביבה",
    RoleId: 6,
    MkId: 956,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/InternalAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 5,
    CommitteeName: "ועדת הפנים והגנת הסביבה",
    RoleId: 6,
    MkId: 1108,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/InternalAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 5,
    CommitteeName: "ועדת הפנים והגנת הסביבה",
    RoleId: 6,
    MkId: 964,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/InternalAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 5,
    CommitteeName: "ועדת הפנים והגנת הסביבה",
    RoleId: 6,
    MkId: 992,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/InternalAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 5,
    CommitteeName: "ועדת הפנים והגנת הסביבה",
    RoleId: 6,
    MkId: 1091,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/InternalAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 5,
    CommitteeName: "ועדת הפנים והגנת הסביבה",
    RoleId: 6,
    MkId: 1111,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/InternalAffairs/Pages/default.aspx",
  },
  {
    CommitteeId: 6,
    CommitteeName: "ועדת החוקה, חוק ומשפט",
    RoleId: 4,
    MkId: 1067,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/huka/Pages/default.aspx",
  },
  {
    CommitteeId: 6,
    CommitteeName: "ועדת החוקה, חוק ומשפט",
    RoleId: 6,
    MkId: 860,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/huka/Pages/default.aspx",
  },
  {
    CommitteeId: 6,
    CommitteeName: "ועדת החוקה, חוק ומשפט",
    RoleId: 6,
    MkId: 861,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/huka/Pages/default.aspx",
  },
  {
    CommitteeId: 6,
    CommitteeName: "ועדת החוקה, חוק ומשפט",
    RoleId: 6,
    MkId: 1097,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/huka/Pages/default.aspx",
  },
  {
    CommitteeId: 6,
    CommitteeName: "ועדת החוקה, חוק ומשפט",
    RoleId: 6,
    MkId: 1098,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/huka/Pages/default.aspx",
  },
  {
    CommitteeId: 6,
    CommitteeName: "ועדת החוקה, חוק ומשפט",
    RoleId: 6,
    MkId: 1059,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/huka/Pages/default.aspx",
  },
  {
    CommitteeId: 6,
    CommitteeName: "ועדת החוקה, חוק ומשפט",
    RoleId: 6,
    MkId: 1030,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/huka/Pages/default.aspx",
  },
  {
    CommitteeId: 6,
    CommitteeName: "ועדת החוקה, חוק ומשפט",
    RoleId: 6,
    MkId: 1013,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/huka/Pages/default.aspx",
  },
  {
    CommitteeId: 6,
    CommitteeName: "ועדת החוקה, חוק ומשפט",
    RoleId: 6,
    MkId: 1105,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/huka/Pages/default.aspx",
  },
  {
    CommitteeId: 6,
    CommitteeName: "ועדת החוקה, חוק ומשפט",
    RoleId: 6,
    MkId: 1119,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/huka/Pages/default.aspx",
  },
  {
    CommitteeId: 6,
    CommitteeName: "ועדת החוקה, חוק ומשפט",
    RoleId: 6,
    MkId: 956,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/huka/Pages/default.aspx",
  },
  {
    CommitteeId: 6,
    CommitteeName: "ועדת החוקה, חוק ומשפט",
    RoleId: 6,
    MkId: 995,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/huka/Pages/default.aspx",
  },
  {
    CommitteeId: 6,
    CommitteeName: "ועדת החוקה, חוק ומשפט",
    RoleId: 6,
    MkId: 1007,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/huka/Pages/default.aspx",
  },
  {
    CommitteeId: 6,
    CommitteeName: "ועדת החוקה, חוק ומשפט",
    RoleId: 6,
    MkId: 987,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/huka/Pages/default.aspx",
  },
  {
    CommitteeId: 6,
    CommitteeName: "ועדת החוקה, חוק ומשפט",
    RoleId: 6,
    MkId: 1114,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/huka/Pages/default.aspx",
  },
  {
    CommitteeId: 6,
    CommitteeName: "ועדת החוקה, חוק ומשפט",
    RoleId: 6,
    MkId: 1066,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/huka/Pages/default.aspx",
  },
  {
    CommitteeId: 27,
    CommitteeName: "ועדת העלייה, הקליטה והתפוצות",
    RoleId: 4,
    MkId: 951,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/Immigration/Pages/default.aspx",
  },
  {
    CommitteeId: 27,
    CommitteeName: "ועדת העלייה, הקליטה והתפוצות",
    RoleId: 6,
    MkId: 1116,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Immigration/Pages/default.aspx",
  },
  {
    CommitteeId: 27,
    CommitteeName: "ועדת העלייה, הקליטה והתפוצות",
    RoleId: 6,
    MkId: 1088,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Immigration/Pages/default.aspx",
  },
  {
    CommitteeId: 27,
    CommitteeName: "ועדת העלייה, הקליטה והתפוצות",
    RoleId: 6,
    MkId: 914,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Immigration/Pages/default.aspx",
  },
  {
    CommitteeId: 27,
    CommitteeName: "ועדת העלייה, הקליטה והתפוצות",
    RoleId: 6,
    MkId: 1049,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Immigration/Pages/default.aspx",
  },
  {
    CommitteeId: 27,
    CommitteeName: "ועדת העלייה, הקליטה והתפוצות",
    RoleId: 6,
    MkId: 1125,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Immigration/Pages/default.aspx",
  },
  {
    CommitteeId: 27,
    CommitteeName: "ועדת העלייה, הקליטה והתפוצות",
    RoleId: 6,
    MkId: 1043,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Immigration/Pages/default.aspx",
  },
  {
    CommitteeId: 27,
    CommitteeName: "ועדת העלייה, הקליטה והתפוצות",
    RoleId: 6,
    MkId: 1090,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Immigration/Pages/default.aspx",
  },
  {
    CommitteeId: 27,
    CommitteeName: "ועדת העלייה, הקליטה והתפוצות",
    RoleId: 6,
    MkId: 1076,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Immigration/Pages/default.aspx",
  },
  {
    CommitteeId: 27,
    CommitteeName: "ועדת העלייה, הקליטה והתפוצות",
    RoleId: 6,
    MkId: 1118,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Immigration/Pages/default.aspx",
  },
  {
    CommitteeId: 27,
    CommitteeName: "ועדת העלייה, הקליטה והתפוצות",
    RoleId: 6,
    MkId: 1122,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Immigration/Pages/default.aspx",
  },
  {
    CommitteeId: 27,
    CommitteeName: "ועדת העלייה, הקליטה והתפוצות",
    RoleId: 6,
    MkId: 1110,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Immigration/Pages/default.aspx",
  },
  {
    CommitteeId: 27,
    CommitteeName: "ועדת העלייה, הקליטה והתפוצות",
    RoleId: 6,
    MkId: 1001,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Immigration/Pages/default.aspx",
  },
  {
    CommitteeId: 27,
    CommitteeName: "ועדת העלייה, הקליטה והתפוצות",
    RoleId: 6,
    MkId: 1066,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Immigration/Pages/default.aspx",
  },
  {
    CommitteeId: 27,
    CommitteeName: "ועדת העלייה, הקליטה והתפוצות",
    RoleId: 6,
    MkId: 899,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Immigration/Pages/default.aspx",
  },
  {
    CommitteeId: 8,
    CommitteeName: "ועדת החינוך, התרבות והספורט",
    RoleId: 4,
    MkId: 1043,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/Education/Pages/default.aspx",
  },
  {
    CommitteeId: 8,
    CommitteeName: "ועדת החינוך, התרבות והספורט",
    RoleId: 6,
    MkId: 1126,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Education/Pages/default.aspx",
  },
  {
    CommitteeId: 8,
    CommitteeName: "ועדת החינוך, התרבות והספורט",
    RoleId: 6,
    MkId: 1088,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Education/Pages/default.aspx",
  },
  {
    CommitteeId: 8,
    CommitteeName: "ועדת החינוך, התרבות והספורט",
    RoleId: 6,
    MkId: 1042,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Education/Pages/default.aspx",
  },
  {
    CommitteeId: 8,
    CommitteeName: "ועדת החינוך, התרבות והספורט",
    RoleId: 6,
    MkId: 1085,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Education/Pages/default.aspx",
  },
  {
    CommitteeId: 8,
    CommitteeName: "ועדת החינוך, התרבות והספורט",
    RoleId: 6,
    MkId: 1059,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Education/Pages/default.aspx",
  },
  {
    CommitteeId: 8,
    CommitteeName: "ועדת החינוך, התרבות והספורט",
    RoleId: 6,
    MkId: 1060,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Education/Pages/default.aspx",
  },
  {
    CommitteeId: 8,
    CommitteeName: "ועדת החינוך, התרבות והספורט",
    RoleId: 6,
    MkId: 1050,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Education/Pages/default.aspx",
  },
  {
    CommitteeId: 8,
    CommitteeName: "ועדת החינוך, התרבות והספורט",
    RoleId: 6,
    MkId: 1082,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Education/Pages/default.aspx",
  },
  {
    CommitteeId: 8,
    CommitteeName: "ועדת החינוך, התרבות והספורט",
    RoleId: 6,
    MkId: 1122,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Education/Pages/default.aspx",
  },
  {
    CommitteeId: 8,
    CommitteeName: "ועדת החינוך, התרבות והספורט",
    RoleId: 6,
    MkId: 994,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Education/Pages/default.aspx",
  },
  {
    CommitteeId: 8,
    CommitteeName: "ועדת החינוך, התרבות והספורט",
    RoleId: 6,
    MkId: 1108,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Education/Pages/default.aspx",
  },
  {
    CommitteeId: 8,
    CommitteeName: "ועדת החינוך, התרבות והספורט",
    RoleId: 6,
    MkId: 964,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Education/Pages/default.aspx",
  },
  {
    CommitteeId: 8,
    CommitteeName: "ועדת החינוך, התרבות והספורט",
    RoleId: 6,
    MkId: 1079,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Education/Pages/default.aspx",
  },
  {
    CommitteeId: 8,
    CommitteeName: "ועדת החינוך, התרבות והספורט",
    RoleId: 6,
    MkId: 1018,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Education/Pages/default.aspx",
  },
  {
    CommitteeId: 28,
    CommitteeName: "ועדת העבודה והרווחה",
    RoleId: 4,
    MkId: 754,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/Labor/Pages/default.aspx",
  },
  {
    CommitteeId: 28,
    CommitteeName: "ועדת העבודה והרווחה",
    RoleId: 6,
    MkId: 1093,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Labor/Pages/default.aspx",
  },
  {
    CommitteeId: 28,
    CommitteeName: "ועדת העבודה והרווחה",
    RoleId: 6,
    MkId: 1094,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Labor/Pages/default.aspx",
  },
  {
    CommitteeId: 28,
    CommitteeName: "ועדת העבודה והרווחה",
    RoleId: 6,
    MkId: 1098,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Labor/Pages/default.aspx",
  },
  {
    CommitteeId: 28,
    CommitteeName: "ועדת העבודה והרווחה",
    RoleId: 6,
    MkId: 1059,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Labor/Pages/default.aspx",
  },
  {
    CommitteeId: 28,
    CommitteeName: "ועדת העבודה והרווחה",
    RoleId: 6,
    MkId: 1060,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Labor/Pages/default.aspx",
  },
  {
    CommitteeId: 28,
    CommitteeName: "ועדת העבודה והרווחה",
    RoleId: 6,
    MkId: 1000,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Labor/Pages/default.aspx",
  },
  {
    CommitteeId: 28,
    CommitteeName: "ועדת העבודה והרווחה",
    RoleId: 6,
    MkId: 874,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Labor/Pages/default.aspx",
  },
  {
    CommitteeId: 28,
    CommitteeName: "ועדת העבודה והרווחה",
    RoleId: 6,
    MkId: 1115,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Labor/Pages/default.aspx",
  },
  {
    CommitteeId: 28,
    CommitteeName: "ועדת העבודה והרווחה",
    RoleId: 6,
    MkId: 1122,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Labor/Pages/default.aspx",
  },
  {
    CommitteeId: 28,
    CommitteeName: "ועדת העבודה והרווחה",
    RoleId: 6,
    MkId: 994,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Labor/Pages/default.aspx",
  },
  {
    CommitteeId: 28,
    CommitteeName: "ועדת העבודה והרווחה",
    RoleId: 6,
    MkId: 1108,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Labor/Pages/default.aspx",
  },
  {
    CommitteeId: 28,
    CommitteeName: "ועדת העבודה והרווחה",
    RoleId: 6,
    MkId: 992,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Labor/Pages/default.aspx",
  },
  {
    CommitteeId: 28,
    CommitteeName: "ועדת העבודה והרווחה",
    RoleId: 6,
    MkId: 1068,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Labor/Pages/default.aspx",
  },
  {
    CommitteeId: 28,
    CommitteeName: "ועדת העבודה והרווחה",
    RoleId: 6,
    MkId: 948,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Labor/Pages/default.aspx",
  },
  {
    CommitteeId: 10,
    CommitteeName: "הוועדה לענייני ביקורת המדינה",
    RoleId: 4,
    MkId: 876,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/StateControl/Pages/default.aspx",
  },
  {
    CommitteeId: 10,
    CommitteeName: "הוועדה לענייני ביקורת המדינה",
    RoleId: 6,
    MkId: 1093,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/StateControl/Pages/default.aspx",
  },
  {
    CommitteeId: 10,
    CommitteeName: "הוועדה לענייני ביקורת המדינה",
    RoleId: 6,
    MkId: 915,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/StateControl/Pages/default.aspx",
  },
  {
    CommitteeId: 10,
    CommitteeName: "הוועדה לענייני ביקורת המדינה",
    RoleId: 6,
    MkId: 1097,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/StateControl/Pages/default.aspx",
  },
  {
    CommitteeId: 10,
    CommitteeName: "הוועדה לענייני ביקורת המדינה",
    RoleId: 6,
    MkId: 1098,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/StateControl/Pages/default.aspx",
  },
  {
    CommitteeId: 10,
    CommitteeName: "הוועדה לענייני ביקורת המדינה",
    RoleId: 6,
    MkId: 1109,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/StateControl/Pages/default.aspx",
  },
  {
    CommitteeId: 10,
    CommitteeName: "הוועדה לענייני ביקורת המדינה",
    RoleId: 6,
    MkId: 978,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/StateControl/Pages/default.aspx",
  },
  {
    CommitteeId: 10,
    CommitteeName: "הוועדה לענייני ביקורת המדינה",
    RoleId: 6,
    MkId: 1111,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/StateControl/Pages/default.aspx",
  },
  {
    CommitteeId: 10,
    CommitteeName: "הוועדה לענייני ביקורת המדינה",
    RoleId: 6,
    MkId: 1117,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/StateControl/Pages/default.aspx",
  },
  {
    CommitteeId: 10,
    CommitteeName: "הוועדה לענייני ביקורת המדינה",
    RoleId: 6,
    MkId: 1123,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/StateControl/Pages/default.aspx",
  },
  {
    CommitteeId: 11,
    CommitteeName: "הוועדה לקידום מעמד האישה ולשוויון מגדרי",
    RoleId: 4,
    MkId: 905,
    RoleName: "יושבת-ראש",
    CommitteeLink: "/Activity/committees/Women/Pages/default.aspx",
  },
  {
    CommitteeId: 11,
    CommitteeName: "הוועדה לקידום מעמד האישה ולשוויון מגדרי",
    RoleId: 6,
    MkId: 915,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Women/Pages/default.aspx",
  },
  {
    CommitteeId: 11,
    CommitteeName: "הוועדה לקידום מעמד האישה ולשוויון מגדרי",
    RoleId: 6,
    MkId: 1100,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Women/Pages/default.aspx",
  },
  {
    CommitteeId: 11,
    CommitteeName: "הוועדה לקידום מעמד האישה ולשוויון מגדרי",
    RoleId: 6,
    MkId: 1032,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Women/Pages/default.aspx",
  },
  {
    CommitteeId: 11,
    CommitteeName: "הוועדה לקידום מעמד האישה ולשוויון מגדרי",
    RoleId: 6,
    MkId: 1118,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Women/Pages/default.aspx",
  },
  {
    CommitteeId: 11,
    CommitteeName: "הוועדה לקידום מעמד האישה ולשוויון מגדרי",
    RoleId: 6,
    MkId: 995,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Women/Pages/default.aspx",
  },
  {
    CommitteeId: 11,
    CommitteeName: "הוועדה לקידום מעמד האישה ולשוויון מגדרי",
    RoleId: 6,
    MkId: 1091,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Women/Pages/default.aspx",
  },
  {
    CommitteeId: 11,
    CommitteeName: "הוועדה לקידום מעמד האישה ולשוויון מגדרי",
    RoleId: 6,
    MkId: 1018,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Women/Pages/default.aspx",
  },
  {
    CommitteeId: 13,
    CommitteeName: "ועדת  המדע  והטכנולוגיה",
    RoleId: 4,
    MkId: 938,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/Science/Pages/default.aspx",
  },
  {
    CommitteeId: 13,
    CommitteeName: "ועדת  המדע  והטכנולוגיה",
    RoleId: 6,
    MkId: 1125,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Science/Pages/default.aspx",
  },
  {
    CommitteeId: 13,
    CommitteeName: "ועדת  המדע  והטכנולוגיה",
    RoleId: 6,
    MkId: 1103,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Science/Pages/default.aspx",
  },
  {
    CommitteeId: 13,
    CommitteeName: "ועדת  המדע  והטכנולוגיה",
    RoleId: 6,
    MkId: 1061,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Science/Pages/default.aspx",
  },
  {
    CommitteeId: 13,
    CommitteeName: "ועדת  המדע  והטכנולוגיה",
    RoleId: 6,
    MkId: 998,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Science/Pages/default.aspx",
  },
  {
    CommitteeId: 13,
    CommitteeName: "ועדת  המדע  והטכנולוגיה",
    RoleId: 6,
    MkId: 1120,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Science/Pages/default.aspx",
  },
  {
    CommitteeId: 13,
    CommitteeName: "ועדת  המדע  והטכנולוגיה",
    RoleId: 6,
    MkId: 1118,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Science/Pages/default.aspx",
  },
  {
    CommitteeId: 13,
    CommitteeName: "ועדת  המדע  והטכנולוגיה",
    RoleId: 6,
    MkId: 1121,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Science/Pages/default.aspx",
  },
  {
    CommitteeId: 13,
    CommitteeName: "ועדת  המדע  והטכנולוגיה",
    RoleId: 6,
    MkId: 837,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Science/Pages/default.aspx",
  },
  {
    CommitteeId: 13,
    CommitteeName: "ועדת  המדע  והטכנולוגיה",
    RoleId: 6,
    MkId: 1124,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Science/Pages/default.aspx",
  },
  {
    CommitteeId: 13,
    CommitteeName: "ועדת  המדע  והטכנולוגיה",
    RoleId: 6,
    MkId: 978,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Science/Pages/default.aspx",
  },
  {
    CommitteeId: 13,
    CommitteeName: "ועדת  המדע  והטכנולוגיה",
    RoleId: 6,
    MkId: 1091,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Science/Pages/default.aspx",
  },
  {
    CommitteeId: 13,
    CommitteeName: "ועדת  המדע  והטכנולוגיה",
    RoleId: 6,
    MkId: 1112,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Science/Pages/default.aspx",
  },
  {
    CommitteeId: 752,
    CommitteeName: "ועדת הבריאות",
    RoleId: 4,
    MkId: 1115,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/health/Pages/default.aspx",
  },
  {
    CommitteeId: 752,
    CommitteeName: "ועדת הבריאות",
    RoleId: 6,
    MkId: 1059,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/health/Pages/default.aspx",
  },
  {
    CommitteeId: 752,
    CommitteeName: "ועדת הבריאות",
    RoleId: 6,
    MkId: 1045,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/health/Pages/default.aspx",
  },
  {
    CommitteeId: 752,
    CommitteeName: "ועדת הבריאות",
    RoleId: 6,
    MkId: 1060,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/health/Pages/default.aspx",
  },
  {
    CommitteeId: 752,
    CommitteeName: "ועדת הבריאות",
    RoleId: 6,
    MkId: 1103,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/health/Pages/default.aspx",
  },
  {
    CommitteeId: 752,
    CommitteeName: "ועדת הבריאות",
    RoleId: 6,
    MkId: 208,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/health/Pages/default.aspx",
  },
  {
    CommitteeId: 752,
    CommitteeName: "ועדת הבריאות",
    RoleId: 6,
    MkId: 1000,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/health/Pages/default.aspx",
  },
  {
    CommitteeId: 752,
    CommitteeName: "ועדת הבריאות",
    RoleId: 6,
    MkId: 1061,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/health/Pages/default.aspx",
  },
  {
    CommitteeId: 752,
    CommitteeName: "ועדת הבריאות",
    RoleId: 6,
    MkId: 1127,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/health/Pages/default.aspx",
  },
  {
    CommitteeId: 752,
    CommitteeName: "ועדת הבריאות",
    RoleId: 6,
    MkId: 1076,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/health/Pages/default.aspx",
  },
  {
    CommitteeId: 752,
    CommitteeName: "ועדת הבריאות",
    RoleId: 6,
    MkId: 1108,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/health/Pages/default.aspx",
  },
  {
    CommitteeId: 752,
    CommitteeName: "ועדת הבריאות",
    RoleId: 6,
    MkId: 1117,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/health/Pages/default.aspx",
  },
  {
    CommitteeId: 752,
    CommitteeName: "ועדת הבריאות",
    RoleId: 6,
    MkId: 1018,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/health/Pages/default.aspx",
  },
  {
    CommitteeId: 752,
    CommitteeName: "ועדת הבריאות",
    RoleId: 6,
    MkId: 1123,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/health/Pages/default.aspx",
  },
  {
    CommitteeId: 750,
    CommitteeName: "הוועדה לביטחון לאומי",
    RoleId: 4,
    MkId: 1110,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/InternalSecurity/Pages/default.aspx",
  },
  {
    CommitteeId: 750,
    CommitteeName: "הוועדה לביטחון לאומי",
    RoleId: 6,
    MkId: 754,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/InternalSecurity/Pages/default.aspx",
  },
  {
    CommitteeId: 750,
    CommitteeName: "הוועדה לביטחון לאומי",
    RoleId: 6,
    MkId: 1093,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/InternalSecurity/Pages/default.aspx",
  },
  {
    CommitteeId: 750,
    CommitteeName: "הוועדה לביטחון לאומי",
    RoleId: 6,
    MkId: 1088,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/InternalSecurity/Pages/default.aspx",
  },
  {
    CommitteeId: 750,
    CommitteeName: "הוועדה לביטחון לאומי",
    RoleId: 6,
    MkId: 915,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/InternalSecurity/Pages/default.aspx",
  },
  {
    CommitteeId: 750,
    CommitteeName: "הוועדה לביטחון לאומי",
    RoleId: 6,
    MkId: 1044,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/InternalSecurity/Pages/default.aspx",
  },
  {
    CommitteeId: 750,
    CommitteeName: "הוועדה לביטחון לאומי",
    RoleId: 6,
    MkId: 1120,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/InternalSecurity/Pages/default.aspx",
  },
  {
    CommitteeId: 750,
    CommitteeName: "הוועדה לביטחון לאומי",
    RoleId: 6,
    MkId: 1121,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/InternalSecurity/Pages/default.aspx",
  },
  {
    CommitteeId: 750,
    CommitteeName: "הוועדה לביטחון לאומי",
    RoleId: 6,
    MkId: 1109,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/InternalSecurity/Pages/default.aspx",
  },
  {
    CommitteeId: 750,
    CommitteeName: "הוועדה לביטחון לאומי",
    RoleId: 6,
    MkId: 837,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/InternalSecurity/Pages/default.aspx",
  },
  {
    CommitteeId: 750,
    CommitteeName: "הוועדה לביטחון לאומי",
    RoleId: 6,
    MkId: 987,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/InternalSecurity/Pages/default.aspx",
  },
  {
    CommitteeId: 750,
    CommitteeName: "הוועדה לביטחון לאומי",
    RoleId: 6,
    MkId: 1066,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/InternalSecurity/Pages/default.aspx",
  },
  {
    CommitteeId: 750,
    CommitteeName: "הוועדה לביטחון לאומי",
    RoleId: 6,
    MkId: 1112,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/InternalSecurity/Pages/default.aspx",
  },
  {
    CommitteeId: 784,
    CommitteeName: "הוועדה למיזמים ציבוריים",
    RoleId: 4,
    MkId: 1090,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/PublicProjects/Pages/default.aspx",
  },
  {
    CommitteeId: 784,
    CommitteeName: "הוועדה למיזמים ציבוריים",
    RoleId: 6,
    MkId: 1116,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/PublicProjects/Pages/default.aspx",
  },
  {
    CommitteeId: 784,
    CommitteeName: "הוועדה למיזמים ציבוריים",
    RoleId: 6,
    MkId: 1022,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/PublicProjects/Pages/default.aspx",
  },
  {
    CommitteeId: 784,
    CommitteeName: "הוועדה למיזמים ציבוריים",
    RoleId: 6,
    MkId: 1097,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/PublicProjects/Pages/default.aspx",
  },
  {
    CommitteeId: 784,
    CommitteeName: "הוועדה למיזמים ציבוריים",
    RoleId: 6,
    MkId: 35,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/PublicProjects/Pages/default.aspx",
  },
  {
    CommitteeId: 784,
    CommitteeName: "הוועדה למיזמים ציבוריים",
    RoleId: 6,
    MkId: 1100,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/PublicProjects/Pages/default.aspx",
  },
  {
    CommitteeId: 784,
    CommitteeName: "הוועדה למיזמים ציבוריים",
    RoleId: 6,
    MkId: 1032,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/PublicProjects/Pages/default.aspx",
  },
  {
    CommitteeId: 784,
    CommitteeName: "הוועדה למיזמים ציבוריים",
    RoleId: 6,
    MkId: 1091,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/PublicProjects/Pages/default.aspx",
  },
  {
    CommitteeId: 784,
    CommitteeName: "הוועדה למיזמים ציבוריים",
    RoleId: 6,
    MkId: 982,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/PublicProjects/Pages/default.aspx",
  },
  {
    CommitteeId: 14,
    CommitteeName: "ועדת האתיקה",
    RoleId: 4,
    MkId: 1117,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/Ethics/Pages/default.aspx",
  },
  {
    CommitteeId: 14,
    CommitteeName: "ועדת האתיקה",
    RoleId: 6,
    MkId: 1060,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Ethics/Pages/default.aspx",
  },
  {
    CommitteeId: 14,
    CommitteeName: "ועדת האתיקה",
    RoleId: 6,
    MkId: 1106,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Ethics/Pages/default.aspx",
  },
  {
    CommitteeId: 14,
    CommitteeName: "ועדת האתיקה",
    RoleId: 6,
    MkId: 905,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Ethics/Pages/default.aspx",
  },
  {
    CommitteeId: 779,
    CommitteeName: 'הוועדה המיוחדת לדיון בהצעת החוק לתיקון פקודת המשטרה (סמכויות), התשפ"ג-2022 (פ/80/25)',
    RoleId: 4,
    MkId: 976,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/police/Pages/default.aspx",
  },
  {
    CommitteeId: 779,
    CommitteeName: 'הוועדה המיוחדת לדיון בהצעת החוק לתיקון פקודת המשטרה (סמכויות), התשפ"ג-2022 (פ/80/25)',
    RoleId: 6,
    MkId: 970,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/police/Pages/default.aspx",
  },
  {
    CommitteeId: 779,
    CommitteeName: 'הוועדה המיוחדת לדיון בהצעת החוק לתיקון פקודת המשטרה (סמכויות), התשפ"ג-2022 (פ/80/25)',
    RoleId: 6,
    MkId: 1093,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/police/Pages/default.aspx",
  },
  {
    CommitteeId: 779,
    CommitteeName: 'הוועדה המיוחדת לדיון בהצעת החוק לתיקון פקודת המשטרה (סמכויות), התשפ"ג-2022 (פ/80/25)',
    RoleId: 6,
    MkId: 915,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/police/Pages/default.aspx",
  },
  {
    CommitteeId: 779,
    CommitteeName: 'הוועדה המיוחדת לדיון בהצעת החוק לתיקון פקודת המשטרה (סמכויות), התשפ"ג-2022 (פ/80/25)',
    RoleId: 6,
    MkId: 1013,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/police/Pages/default.aspx",
  },
  {
    CommitteeId: 779,
    CommitteeName: 'הוועדה המיוחדת לדיון בהצעת החוק לתיקון פקודת המשטרה (סמכויות), התשפ"ג-2022 (פ/80/25)',
    RoleId: 6,
    MkId: 1061,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/police/Pages/default.aspx",
  },
  {
    CommitteeId: 779,
    CommitteeName: 'הוועדה המיוחדת לדיון בהצעת החוק לתיקון פקודת המשטרה (סמכויות), התשפ"ג-2022 (פ/80/25)',
    RoleId: 6,
    MkId: 956,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/police/Pages/default.aspx",
  },
  {
    CommitteeId: 779,
    CommitteeName: 'הוועדה המיוחדת לדיון בהצעת החוק לתיקון פקודת המשטרה (סמכויות), התשפ"ג-2022 (פ/80/25)',
    RoleId: 6,
    MkId: 1107,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/police/Pages/default.aspx",
  },
  {
    CommitteeId: 779,
    CommitteeName: 'הוועדה המיוחדת לדיון בהצעת החוק לתיקון פקודת המשטרה (סמכויות), התשפ"ג-2022 (פ/80/25)',
    RoleId: 6,
    MkId: 1109,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/police/Pages/default.aspx",
  },
  {
    CommitteeId: 779,
    CommitteeName: 'הוועדה המיוחדת לדיון בהצעת החוק לתיקון פקודת המשטרה (סמכויות), התשפ"ג-2022 (פ/80/25)',
    RoleId: 6,
    MkId: 1110,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/police/Pages/default.aspx",
  },
  {
    CommitteeId: 779,
    CommitteeName: 'הוועדה המיוחדת לדיון בהצעת החוק לתיקון פקודת המשטרה (סמכויות), התשפ"ג-2022 (פ/80/25)',
    RoleId: 6,
    MkId: 1111,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/police/Pages/default.aspx",
  },
  {
    CommitteeId: 12,
    CommitteeName: "הוועדה המיוחדת למאבק בשימוש בסמים ובאלכוהול",
    RoleId: 4,
    MkId: 1095,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/Drugs/Pages/default.aspx",
  },
  {
    CommitteeId: 12,
    CommitteeName: "הוועדה המיוחדת למאבק בשימוש בסמים ובאלכוהול",
    RoleId: 6,
    MkId: 1088,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Drugs/Pages/default.aspx",
  },
  {
    CommitteeId: 12,
    CommitteeName: "הוועדה המיוחדת למאבק בשימוש בסמים ובאלכוהול",
    RoleId: 6,
    MkId: 1085,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Drugs/Pages/default.aspx",
  },
  {
    CommitteeId: 12,
    CommitteeName: "הוועדה המיוחדת למאבק בשימוש בסמים ובאלכוהול",
    RoleId: 6,
    MkId: 1061,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Drugs/Pages/default.aspx",
  },
  {
    CommitteeId: 12,
    CommitteeName: "הוועדה המיוחדת למאבק בשימוש בסמים ובאלכוהול",
    RoleId: 6,
    MkId: 1120,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Drugs/Pages/default.aspx",
  },
  {
    CommitteeId: 12,
    CommitteeName: "הוועדה המיוחדת למאבק בשימוש בסמים ובאלכוהול",
    RoleId: 6,
    MkId: 1107,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Drugs/Pages/default.aspx",
  },
  {
    CommitteeId: 12,
    CommitteeName: "הוועדה המיוחדת למאבק בשימוש בסמים ובאלכוהול",
    RoleId: 6,
    MkId: 987,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Drugs/Pages/default.aspx",
  },
  {
    CommitteeId: 12,
    CommitteeName: "הוועדה המיוחדת למאבק בשימוש בסמים ובאלכוהול",
    RoleId: 6,
    MkId: 1114,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Drugs/Pages/default.aspx",
  },
  {
    CommitteeId: 780,
    CommitteeName: "הוועדה המיוחדת לחיזוק ופיתוח הנגב והגליל",
    RoleId: 4,
    MkId: 1003,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/negevgalil/Pages/default.aspx",
  },
  {
    CommitteeId: 781,
    CommitteeName: "הוועדה המיוחדת לצמצום פערים חברתיים בפריפריה",
    RoleId: 4,
    MkId: 1097,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/periphery/Pages/default.aspx",
  },
  {
    CommitteeId: 25,
    CommitteeName: "הוועדה המיוחדת לזכויות הילד",
    RoleId: 4,
    MkId: 1100,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/Children/Pages/default.aspx",
  },
  {
    CommitteeId: 780,
    CommitteeName: "הוועדה המיוחדת לחיזוק ופיתוח הנגב והגליל",
    RoleId: 6,
    MkId: 1093,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/negevgalil/Pages/default.aspx",
  },
  {
    CommitteeId: 781,
    CommitteeName: "הוועדה המיוחדת לצמצום פערים חברתיים בפריפריה",
    RoleId: 6,
    MkId: 861,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/periphery/Pages/default.aspx",
  },
  {
    CommitteeId: 25,
    CommitteeName: "הוועדה המיוחדת לזכויות הילד",
    RoleId: 6,
    MkId: 1094,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Children/Pages/default.aspx",
  },
  {
    CommitteeId: 781,
    CommitteeName: "הוועדה המיוחדת לצמצום פערים חברתיים בפריפריה",
    RoleId: 6,
    MkId: 1094,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/periphery/Pages/default.aspx",
  },
  {
    CommitteeId: 780,
    CommitteeName: "הוועדה המיוחדת לחיזוק ופיתוח הנגב והגליל",
    RoleId: 6,
    MkId: 1125,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/negevgalil/Pages/default.aspx",
  },
  {
    CommitteeId: 25,
    CommitteeName: "הוועדה המיוחדת לזכויות הילד",
    RoleId: 6,
    MkId: 1098,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Children/Pages/default.aspx",
  },
  {
    CommitteeId: 780,
    CommitteeName: "הוועדה המיוחדת לחיזוק ופיתוח הנגב והגליל",
    RoleId: 6,
    MkId: 1045,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/negevgalil/Pages/default.aspx",
  },
  {
    CommitteeId: 781,
    CommitteeName: "הוועדה המיוחדת לצמצום פערים חברתיים בפריפריה",
    RoleId: 6,
    MkId: 1103,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/periphery/Pages/default.aspx",
  },
  {
    CommitteeId: 781,
    CommitteeName: "הוועדה המיוחדת לצמצום פערים חברתיים בפריפריה",
    RoleId: 6,
    MkId: 874,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/periphery/Pages/default.aspx",
  },
  {
    CommitteeId: 25,
    CommitteeName: "הוועדה המיוחדת לזכויות הילד",
    RoleId: 6,
    MkId: 1120,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Children/Pages/default.aspx",
  },
  {
    CommitteeId: 780,
    CommitteeName: "הוועדה המיוחדת לחיזוק ופיתוח הנגב והגליל",
    RoleId: 6,
    MkId: 1076,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/negevgalil/Pages/default.aspx",
  },
  {
    CommitteeId: 780,
    CommitteeName: "הוועדה המיוחדת לחיזוק ופיתוח הנגב והגליל",
    RoleId: 6,
    MkId: 1115,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/negevgalil/Pages/default.aspx",
  },
  {
    CommitteeId: 780,
    CommitteeName: "הוועדה המיוחדת לחיזוק ופיתוח הנגב והגליל",
    RoleId: 6,
    MkId: 1119,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/negevgalil/Pages/default.aspx",
  },
  {
    CommitteeId: 781,
    CommitteeName: "הוועדה המיוחדת לצמצום פערים חברתיים בפריפריה",
    RoleId: 6,
    MkId: 1122,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/periphery/Pages/default.aspx",
  },
  {
    CommitteeId: 780,
    CommitteeName: "הוועדה המיוחדת לחיזוק ופיתוח הנגב והגליל",
    RoleId: 6,
    MkId: 1121,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/negevgalil/Pages/default.aspx",
  },
  {
    CommitteeId: 780,
    CommitteeName: "הוועדה המיוחדת לחיזוק ופיתוח הנגב והגליל",
    RoleId: 6,
    MkId: 964,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/negevgalil/Pages/default.aspx",
  },
  {
    CommitteeId: 780,
    CommitteeName: "הוועדה המיוחדת לחיזוק ופיתוח הנגב והגליל",
    RoleId: 6,
    MkId: 951,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/negevgalil/Pages/default.aspx",
  },
  {
    CommitteeId: 781,
    CommitteeName: "הוועדה המיוחדת לצמצום פערים חברתיים בפריפריה",
    RoleId: 6,
    MkId: 1124,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/periphery/Pages/default.aspx",
  },
  {
    CommitteeId: 780,
    CommitteeName: "הוועדה המיוחדת לחיזוק ופיתוח הנגב והגליל",
    RoleId: 6,
    MkId: 1079,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/negevgalil/Pages/default.aspx",
  },
  {
    CommitteeId: 780,
    CommitteeName: "הוועדה המיוחדת לחיזוק ופיתוח הנגב והגליל",
    RoleId: 6,
    MkId: 1114,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/negevgalil/Pages/default.aspx",
  },
  {
    CommitteeId: 25,
    CommitteeName: "הוועדה המיוחדת לזכויות הילד",
    RoleId: 6,
    MkId: 1117,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Children/Pages/default.aspx",
  },
  {
    CommitteeId: 780,
    CommitteeName: "הוועדה המיוחדת לחיזוק ופיתוח הנגב והגליל",
    RoleId: 6,
    MkId: 1117,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/negevgalil/Pages/default.aspx",
  },
  {
    CommitteeId: 781,
    CommitteeName: "הוועדה המיוחדת לצמצום פערים חברתיים בפריפריה",
    RoleId: 6,
    MkId: 1018,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/periphery/Pages/default.aspx",
  },
  {
    CommitteeId: 25,
    CommitteeName: "הוועדה המיוחדת לזכויות הילד",
    RoleId: 6,
    MkId: 1004,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Children/Pages/default.aspx",
  },
  {
    CommitteeId: 25,
    CommitteeName: "הוועדה המיוחדת לזכויות הילד",
    RoleId: 6,
    MkId: 1123,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Children/Pages/default.aspx",
  },
  {
    CommitteeId: 25,
    CommitteeName: "הוועדה המיוחדת לזכויות הילד",
    RoleId: 6,
    MkId: 948,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Children/Pages/default.aspx",
  },
  {
    CommitteeId: 25,
    CommitteeName: "הוועדה המיוחדת לזכויות הילד",
    RoleId: 6,
    MkId: 905,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Children/Pages/default.aspx",
  },
  {
    CommitteeId: 781,
    CommitteeName: "הוועדה המיוחדת לצמצום פערים חברתיים בפריפריה",
    RoleId: 6,
    MkId: 905,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/periphery/Pages/default.aspx",
  },
  {
    CommitteeId: 785,
    CommitteeName: "הוועדה המיוחדת לטיפול בשורדי השואה",
    RoleId: 4,
    MkId: 1006,
    RoleName: "יושבת-ראש",
    CommitteeLink: "/Activity/committees/survivors/Pages/default.aspx",
  },
  {
    CommitteeId: 785,
    CommitteeName: "הוועדה המיוחדת לטיפול בשורדי השואה",
    RoleId: 6,
    MkId: 754,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/survivors/Pages/default.aspx",
  },
  {
    CommitteeId: 785,
    CommitteeName: "הוועדה המיוחדת לטיפול בשורדי השואה",
    RoleId: 6,
    MkId: 1126,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/survivors/Pages/default.aspx",
  },
  {
    CommitteeId: 785,
    CommitteeName: "הוועדה המיוחדת לטיפול בשורדי השואה",
    RoleId: 6,
    MkId: 1125,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/survivors/Pages/default.aspx",
  },
  {
    CommitteeId: 785,
    CommitteeName: "הוועדה המיוחדת לטיפול בשורדי השואה",
    RoleId: 6,
    MkId: 1043,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/survivors/Pages/default.aspx",
  },
  {
    CommitteeId: 785,
    CommitteeName: "הוועדה המיוחדת לטיפול בשורדי השואה",
    RoleId: 6,
    MkId: 1121,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/survivors/Pages/default.aspx",
  },
  {
    CommitteeId: 785,
    CommitteeName: "הוועדה המיוחדת לטיפול בשורדי השואה",
    RoleId: 6,
    MkId: 1110,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/survivors/Pages/default.aspx",
  },
  {
    CommitteeId: 785,
    CommitteeName: "הוועדה המיוחדת לטיפול בשורדי השואה",
    RoleId: 6,
    MkId: 1079,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/survivors/Pages/default.aspx",
  },
  {
    CommitteeId: 785,
    CommitteeName: "הוועדה המיוחדת לטיפול בשורדי השואה",
    RoleId: 6,
    MkId: 1068,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/survivors/Pages/default.aspx",
  },
  {
    CommitteeId: 785,
    CommitteeName: "הוועדה המיוחדת לטיפול בשורדי השואה",
    RoleId: 6,
    MkId: 982,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/survivors/Pages/default.aspx",
  },
  {
    CommitteeId: 15,
    CommitteeName: "הוועדה המיוחדת לעובדים זרים",
    RoleId: 4,
    MkId: 1111,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/Foreign/Pages/default.aspx",
  },
  {
    CommitteeId: 15,
    CommitteeName: "הוועדה המיוחדת לעובדים זרים",
    RoleId: 6,
    MkId: 1093,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Foreign/Pages/default.aspx",
  },
  {
    CommitteeId: 15,
    CommitteeName: "הוועדה המיוחדת לעובדים זרים",
    RoleId: 6,
    MkId: 1085,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Foreign/Pages/default.aspx",
  },
  {
    CommitteeId: 15,
    CommitteeName: "הוועדה המיוחדת לעובדים זרים",
    RoleId: 6,
    MkId: 1104,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Foreign/Pages/default.aspx",
  },
  {
    CommitteeId: 15,
    CommitteeName: "הוועדה המיוחדת לעובדים זרים",
    RoleId: 6,
    MkId: 1119,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Foreign/Pages/default.aspx",
  },
  {
    CommitteeId: 15,
    CommitteeName: "הוועדה המיוחדת לעובדים זרים",
    RoleId: 6,
    MkId: 1121,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Foreign/Pages/default.aspx",
  },
  {
    CommitteeId: 15,
    CommitteeName: "הוועדה המיוחדת לעובדים זרים",
    RoleId: 6,
    MkId: 992,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/Foreign/Pages/default.aspx",
  },
  {
    CommitteeId: 15,
    CommitteeName: "הוועדה המיוחדת לעובדים זרים",
    RoleId: 6,
    MkId: 951,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Foreign/Pages/default.aspx",
  },
  {
    CommitteeId: 15,
    CommitteeName: "הוועדה המיוחדת לעובדים זרים",
    RoleId: 6,
    MkId: 1066,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Foreign/Pages/default.aspx",
  },
  {
    CommitteeId: 783,
    CommitteeName: "הוועדה המיוחדת לענייני הצעירים",
    RoleId: 4,
    MkId: 1082,
    RoleName: "יושבת-ראש",
    CommitteeLink: "/Activity/committees/YoungIsraelis/Pages/default.aspx",
  },
  {
    CommitteeId: 783,
    CommitteeName: "הוועדה המיוחדת לענייני הצעירים",
    RoleId: 6,
    MkId: 1116,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/YoungIsraelis/Pages/default.aspx",
  },
  {
    CommitteeId: 783,
    CommitteeName: "הוועדה המיוחדת לענייני הצעירים",
    RoleId: 6,
    MkId: 1042,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/YoungIsraelis/Pages/default.aspx",
  },
  {
    CommitteeId: 783,
    CommitteeName: "הוועדה המיוחדת לענייני הצעירים",
    RoleId: 6,
    MkId: 1127,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/YoungIsraelis/Pages/default.aspx",
  },
  {
    CommitteeId: 783,
    CommitteeName: "הוועדה המיוחדת לענייני הצעירים",
    RoleId: 6,
    MkId: 1119,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/YoungIsraelis/Pages/default.aspx",
  },
  {
    CommitteeId: 783,
    CommitteeName: "הוועדה המיוחדת לענייני הצעירים",
    RoleId: 6,
    MkId: 1106,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/YoungIsraelis/Pages/default.aspx",
  },
  {
    CommitteeId: 783,
    CommitteeName: "הוועדה המיוחדת לענייני הצעירים",
    RoleId: 6,
    MkId: 1121,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/YoungIsraelis/Pages/default.aspx",
  },
  {
    CommitteeId: 783,
    CommitteeName: "הוועדה המיוחדת לענייני הצעירים",
    RoleId: 6,
    MkId: 1108,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/YoungIsraelis/Pages/default.aspx",
  },
  {
    CommitteeId: 783,
    CommitteeName: "הוועדה המיוחדת לענייני הצעירים",
    RoleId: 6,
    MkId: 964,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/YoungIsraelis/Pages/default.aspx",
  },
  {
    CommitteeId: 783,
    CommitteeName: "הוועדה המיוחדת לענייני הצעירים",
    RoleId: 6,
    MkId: 1124,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/YoungIsraelis/Pages/default.aspx",
  },
  {
    CommitteeId: 783,
    CommitteeName: "הוועדה המיוחדת לענייני הצעירים",
    RoleId: 6,
    MkId: 978,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/YoungIsraelis/Pages/default.aspx",
  },
  {
    CommitteeId: 815,
    CommitteeName: "הוועדה המיוחדת ליישובים בגבול המזרחי",
    RoleId: 4,
    MkId: 1088,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/East/Pages/default.aspx",
  },
  {
    CommitteeId: 815,
    CommitteeName: "הוועדה המיוחדת ליישובים בגבול המזרחי",
    RoleId: 6,
    MkId: 1126,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/East/Pages/default.aspx",
  },
  {
    CommitteeId: 815,
    CommitteeName: "הוועדה המיוחדת ליישובים בגבול המזרחי",
    RoleId: 6,
    MkId: 1125,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/East/Pages/default.aspx",
  },
  {
    CommitteeId: 815,
    CommitteeName: "הוועדה המיוחדת ליישובים בגבול המזרחי",
    RoleId: 6,
    MkId: 1045,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/East/Pages/default.aspx",
  },
  {
    CommitteeId: 815,
    CommitteeName: "הוועדה המיוחדת ליישובים בגבול המזרחי",
    RoleId: 6,
    MkId: 1061,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/East/Pages/default.aspx",
  },
  {
    CommitteeId: 815,
    CommitteeName: "הוועדה המיוחדת ליישובים בגבול המזרחי",
    RoleId: 6,
    MkId: 1120,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/East/Pages/default.aspx",
  },
  {
    CommitteeId: 815,
    CommitteeName: "הוועדה המיוחדת ליישובים בגבול המזרחי",
    RoleId: 6,
    MkId: 951,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/East/Pages/default.aspx",
  },
  {
    CommitteeId: 815,
    CommitteeName: "הוועדה המיוחדת ליישובים בגבול המזרחי",
    RoleId: 6,
    MkId: 1114,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/East/Pages/default.aspx",
  },
  {
    CommitteeId: 815,
    CommitteeName: "הוועדה המיוחדת ליישובים בגבול המזרחי",
    RoleId: 6,
    MkId: 905,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/East/Pages/default.aspx",
  },
  {
    CommitteeId: 788,
    CommitteeName: "הוועדה המיוחדת לתיקונים לחוק יסוד: הממשלה",
    RoleId: 4,
    MkId: 976,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/BasicGov/Pages/default.aspx",
  },
  {
    CommitteeId: 788,
    CommitteeName: "הוועדה המיוחדת לתיקונים לחוק יסוד: הממשלה",
    RoleId: 6,
    MkId: 970,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/BasicGov/Pages/default.aspx",
  },
  {
    CommitteeId: 788,
    CommitteeName: "הוועדה המיוחדת לתיקונים לחוק יסוד: הממשלה",
    RoleId: 6,
    MkId: 1095,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/BasicGov/Pages/default.aspx",
  },
  {
    CommitteeId: 788,
    CommitteeName: "הוועדה המיוחדת לתיקונים לחוק יסוד: הממשלה",
    RoleId: 6,
    MkId: 1049,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/BasicGov/Pages/default.aspx",
  },
  {
    CommitteeId: 788,
    CommitteeName: "הוועדה המיוחדת לתיקונים לחוק יסוד: הממשלה",
    RoleId: 6,
    MkId: 1044,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/BasicGov/Pages/default.aspx",
  },
  {
    CommitteeId: 788,
    CommitteeName: "הוועדה המיוחדת לתיקונים לחוק יסוד: הממשלה",
    RoleId: 6,
    MkId: 1050,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/BasicGov/Pages/default.aspx",
  },
  {
    CommitteeId: 788,
    CommitteeName: "הוועדה המיוחדת לתיקונים לחוק יסוד: הממשלה",
    RoleId: 6,
    MkId: 1013,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/BasicGov/Pages/default.aspx",
  },
  {
    CommitteeId: 788,
    CommitteeName: "הוועדה המיוחדת לתיקונים לחוק יסוד: הממשלה",
    RoleId: 6,
    MkId: 1105,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/BasicGov/Pages/default.aspx",
  },
  {
    CommitteeId: 788,
    CommitteeName: "הוועדה המיוחדת לתיקונים לחוק יסוד: הממשלה",
    RoleId: 6,
    MkId: 956,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/BasicGov/Pages/default.aspx",
  },
  {
    CommitteeId: 788,
    CommitteeName: "הוועדה המיוחדת לתיקונים לחוק יסוד: הממשלה",
    RoleId: 6,
    MkId: 1121,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/BasicGov/Pages/default.aspx",
  },
  {
    CommitteeId: 788,
    CommitteeName: "הוועדה המיוחדת לתיקונים לחוק יסוד: הממשלה",
    RoleId: 6,
    MkId: 1007,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/BasicGov/Pages/default.aspx",
  },
  {
    CommitteeId: 788,
    CommitteeName: "הוועדה המיוחדת לתיקונים לחוק יסוד: הממשלה",
    RoleId: 6,
    MkId: 978,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/BasicGov/Pages/default.aspx",
  },
  {
    CommitteeId: 788,
    CommitteeName: "הוועדה המיוחדת לתיקונים לחוק יסוד: הממשלה",
    RoleId: 6,
    MkId: 1114,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/BasicGov/Pages/default.aspx",
  },
  {
    CommitteeId: 788,
    CommitteeName: "הוועדה המיוחדת לתיקונים לחוק יסוד: הממשלה",
    RoleId: 6,
    MkId: 1117,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/BasicGov/Pages/default.aspx",
  },
  {
    CommitteeId: 788,
    CommitteeName: "הוועדה המיוחדת לתיקונים לחוק יסוד: הממשלה",
    RoleId: 6,
    MkId: 1068,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/BasicGov/Pages/default.aspx",
  },
  {
    CommitteeId: 708,
    CommitteeName: "הוועדה לפיקוח על הקרן לאזרחי ישראל",
    RoleId: 4,
    MkId: 1108,
    RoleName: "יושבת-ראש",
    CommitteeLink: "/Activity/committees/GasFund/Pages/default.aspx",
  },
  {
    CommitteeId: 708,
    CommitteeName: "הוועדה לפיקוח על הקרן לאזרחי ישראל",
    RoleId: 6,
    MkId: 1003,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/GasFund/Pages/default.aspx",
  },
  {
    CommitteeId: 708,
    CommitteeName: "הוועדה לפיקוח על הקרן לאזרחי ישראל",
    RoleId: 6,
    MkId: 1125,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/GasFund/Pages/default.aspx",
  },
  {
    CommitteeId: 708,
    CommitteeName: "הוועדה לפיקוח על הקרן לאזרחי ישראל",
    RoleId: 6,
    MkId: 1045,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/GasFund/Pages/default.aspx",
  },
  {
    CommitteeId: 708,
    CommitteeName: "הוועדה לפיקוח על הקרן לאזרחי ישראל",
    RoleId: 6,
    MkId: 1127,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/GasFund/Pages/default.aspx",
  },
  {
    CommitteeId: 708,
    CommitteeName: "הוועדה לפיקוח על הקרן לאזרחי ישראל",
    RoleId: 6,
    MkId: 214,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/GasFund/Pages/default.aspx",
  },
  {
    CommitteeId: 708,
    CommitteeName: "הוועדה לפיקוח על הקרן לאזרחי ישראל",
    RoleId: 6,
    MkId: 1115,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/GasFund/Pages/default.aspx",
  },
  {
    CommitteeId: 708,
    CommitteeName: "הוועדה לפיקוח על הקרן לאזרחי ישראל",
    RoleId: 6,
    MkId: 1079,
    RoleName: "חברה",
    CommitteeLink: "/Activity/committees/GasFund/Pages/default.aspx",
  },
  {
    CommitteeId: 708,
    CommitteeName: "הוועדה לפיקוח על הקרן לאזרחי ישראל",
    RoleId: 6,
    MkId: 1123,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/GasFund/Pages/default.aspx",
  },
  {
    CommitteeId: 19,
    CommitteeName: "הוועדה המיוחדת לפניות הציבור",
    RoleId: 4,
    MkId: 1001,
    RoleName: "יושב-ראש",
    CommitteeLink: "/Activity/committees/Petitions/Pages/default.aspx",
  },
  {
    CommitteeId: 19,
    CommitteeName: "הוועדה המיוחדת לפניות הציבור",
    RoleId: 6,
    MkId: 1116,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Petitions/Pages/default.aspx",
  },
  {
    CommitteeId: 19,
    CommitteeName: "הוועדה המיוחדת לפניות הציבור",
    RoleId: 6,
    MkId: 1126,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Petitions/Pages/default.aspx",
  },
  {
    CommitteeId: 19,
    CommitteeName: "הוועדה המיוחדת לפניות הציבור",
    RoleId: 6,
    MkId: 1003,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Petitions/Pages/default.aspx",
  },
  {
    CommitteeId: 19,
    CommitteeName: "הוועדה המיוחדת לפניות הציבור",
    RoleId: 6,
    MkId: 1097,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Petitions/Pages/default.aspx",
  },
  {
    CommitteeId: 19,
    CommitteeName: "הוועדה המיוחדת לפניות הציבור",
    RoleId: 6,
    MkId: 1050,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Petitions/Pages/default.aspx",
  },
  {
    CommitteeId: 19,
    CommitteeName: "הוועדה המיוחדת לפניות הציבור",
    RoleId: 6,
    MkId: 998,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Petitions/Pages/default.aspx",
  },
  {
    CommitteeId: 19,
    CommitteeName: "הוועדה המיוחדת לפניות הציבור",
    RoleId: 6,
    MkId: 1007,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Petitions/Pages/default.aspx",
  },
  {
    CommitteeId: 19,
    CommitteeName: "הוועדה המיוחדת לפניות הציבור",
    RoleId: 6,
    MkId: 1123,
    RoleName: "חבר",
    CommitteeLink: "/Activity/committees/Petitions/Pages/default.aspx",
  },
];
